## Questions 1:

### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


## Questions 2:

### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
list1=[]
print("1st list elements:")
for x in range(1,6):
    a=int(input())
    list1.append(a)

list2=[]
print("2nd list elements:")
for y in range(1,6):
    b=int(input())
    list2.append(b)
    
print("1st_list= " , list1)
print("2nd_list= " , list2)
import numpy as np
array1=np.array(list1)
print("1st Array: ",array1)
array2=np.array(list2)
print("2nd Array: ",array2)
array3=np.concatenate((array1,array2))
print("Concatenate Array: ",array3)

sort_array1=np.sort(array1)
print("1st sort Array: ",sort_array1)
sort_array2=np.sort(array2)
print("2nd sort Array: ",sort_array2)
sort_array3=np.sort(array3)
print("3rd sort Array: ",sort_array3)

1st list elements:
7
85
41
79
23
2nd list elements:
25
14
74
78
96
1st_list=  [7, 85, 41, 79, 23]
2nd_list=  [25, 14, 74, 78, 96]
1st Array:  [ 7 85 41 79 23]
2nd Array:  [25 14 74 78 96]
Concatenate Array:  [ 7 85 41 79 23 25 14 74 78 96]
1st sort Array:  [ 7 23 41 79 85]
2nd sort Array:  [14 25 74 78 96]
3rd sort Array:  [ 7 14 23 25 41 74 78 79 85 96]


## Questions 3:

### Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
print("1 Dimensional Array:")
array_1D = np.arange(7)
print(array_1D)
print("Dimension:", array_1D.ndim)
print("Size:",array_1D.size)
print()
print("2 Dimensional Array:")
array_2D = np.arange(9).reshape(3,3)
print(array_2D)
print("Dimension:", array_2D.ndim)
print("Size:",array_2D.size)
print()

1 Dimensional Array:
[0 1 2 3 4 5 6]
Dimension: 1
Size: 7

2 Dimensional Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimension: 2
Size: 9



##  Questions 4:

### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [4]:
array1 = np.array([5,8,9,4,23,15,76,67])
print("1D Array :")
print(array1)
print()
array2= np.reshape(array1, (2, 4))
print("2D Array : ")
print(array2)

1D Array :
[ 5  8  9  4 23 15 76 67]

2D Array : 
[[ 5  8  9  4]
 [23 15 76 67]]


## Questions 5:

### Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [5]:
array1 = np.arange(25).reshape(5,5)
array2 = np.arange(25).reshape(5,5)
V_Stack = np.vstack((array1,array2))
H_Stack = np.hstack((array1,array2))
print("Vertically Stacked : ")
print(V_Stack)
print()
print("Horizontally Stacked : ")
print(H_Stack)

Vertically Stacked : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Horizontally Stacked : 
[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [20 21 22 23 24 20 21 22 23 24]]


## Questions 6:

### How to get unique items and counts of unique items?

In [6]:
list = np.array([5,6,7,6,4,3,5,6,4])

(unique, counts) = np.unique(list, return_counts=True)
print(unique,counts)

[3 4 5 6 7] [1 2 2 3 1]
